### ISSUE TITLE
[Request] Add FXMaster initialization script

### ISSUE THREAD

**Issue by j-schoch** [jinkergm/JAA#1]
Currently installing FXMaster module as well as this module does not allow these files to be available in the FXMaster Cast Spells menu without a lot of manual effort adding them one by one through the FXMaster interface.

If you take a look at how this linked animated asset pack was created, they included a small script and config that will add entries to FXMaster if that module is present.
https://github.com/Jules-Bens-Aa/JB2A_DnD5e/tree/main/scripts

My request is that this module does the same, to provide plug-and-play compatibility with FXMaster.

Thank you!

**Comment by jinkergm** [comment]
I have been working on it, just got bogged down with some other things. Also, I was having a little trouble with working out how to use the code to spit out what I needed, U~man told me how to do it in Discord but I couldn't get it to work for me, but it's probably something I'm doing wrong. I think that file you linked to will help, thanks. I'll try to get back to it soon. I have even making more FX with this very thing in mind. Sorry it's taking so long.
